const cors = require("cors")
const express = require("express")
const multer = require("multer")
const sequelize = require("./configs/db")
const userRoutes = require("./routes/users.routes")
const acomodationsRoutes = require("./routes/acomodations.routes")
const emailAuthRoutes = require("./routes/emailAuth.routes")
const imageRoutes = require("./routes/image.routes")
const app = express()
const port = process.env.PORT || "3001"
const multerConfigs = require("./configs/multer")

sequelize.sync().then(() => console.log("Database conected successfully..."))
app.use(express.json())
app.use(cors())
app.listen(port, console.log("executando..."))
app.use("/users", userRoutes)
app.use("/acomodations", acomodationsRoutes)
app.use("/images", imageRoutes)
app.use("/emailAuth", emailAuthRoutes)
