const cors = require("cors")
const express = require("express")
const sequelize = require("./configs/db")
const userRoutes = require("./routes/users.routes")
const acomodationsRoutes = require("./routes/acomodations.routes")
const emailAuthRoutes = require("./routes/emailAuth.routes")
const path = require("path")
const app = express()
const port = process.env.PORT || "3001"

sequelize.sync().then(() => console.log("Database conected successfully..."))
app.use(express.json())
app.use(cors())
app.use('/profile', express.static(path.resolve(__dirname, "images", "profile")))
app.use('/acomodationImages', express.static(path.resolve(__dirname, "images", "acomodations")))
app.listen(port, console.log("executando..."))
app.use("/users", userRoutes)
app.use("/acomodations", acomodationsRoutes)
app.use("/emailAuth", emailAuthRoutes)
